### ISSUE TITLE
m3u file can contain empty lines

### ISSUE THREAD

**Issue by reb00ter** [Beer4Ever83/ipytv#56]
Now package creates empty channels from empty lines. I think they must be skipped

**Comment by Beer4Ever83** [comment]
I thought about this case extensively and I reached the conclusion that, as per m3u standard, every row that is not a comment or a tag is a url row.
Hence, a blank line is a url row... but with an empty url.
Because of this, I don't think empty lines should be skipped.

**Comment by Beer4Ever83** [comment]
On second thought, I think you may have a point here...
In fact the [RFC for HLS live streams](https://www.rfc-editor.org/rfc/rfc8216#section-4.1) (which uses M3U playlists under the hood) clearly states:

> Each line is a URI, is blank, or starts with the character '#'.  Blank lines are ignored.  Whitespace MUST NOT be present, except for elements in which it is explicitly specified.

So, I'm reopening this issue (apologies for the mess): thanks for submitting it.

**Comment by reb00ter** [comment]
now it fails on processing this sample
```
#EXTM3U url-tvg="http://www.cn.ru/data/tv/schedule.zip" cache=500 deinterlace=1 aspect-ratio=4:3 croppadd=10x10 tvg-shift=0

#EXT-INETRA-CHANNEL-INF: channel-id=10338245 recordable=true age-restriction=16 territory-id=16
#EXT-INETRA-STREAM-INF: aspect-ratio=16:9 has-timeshift=true
#EXTINF:-1 cn-id=10338245 cn-records=1 group-title="Эфир", Первый
http://cache-tv.nsotelecom.ru/streaming/1kanal/16/g2500/playlist.m3u8

#EXT-INETRA-CHANNEL-INF: channel-id=10338258 recordable=true age-restriction=16 territory-id=16
#EXT-INETRA-STREAM-INF: id=233 aspect-ratio=16:9 has-timeshift=true
#EXTINF:-1 cn-id=10338258 cn-records=1 group-title="Эфир", Россия 1
http://cache-tv.nsotelecom.ru/streaming/rossija/16/g2500/playlist.m3u8
```
line left unprocessed

I think that the reason is somewere around `+1` shifting in `_populate`. Didn't you think about skipping empty lines in `loadl`? Now you will skip every line that not fill known patterns, that not seems to be correct
