### ISSUE TITLE
extinf attribute values can be numbers

### ISSUE THREAD

**Issue by reb00ter** [Beer4Ever83/ipytv#57]
in that case they don`t have a quotes

**Comment by Beer4Ever83** [comment]
I have never come across an EXTINF row with no quotes in the attribute list, even when the value is a number. But this doesn't mean it doesn't exist.
Would you be so kind as to provide an example (and the related source) of a playlist with unquoted attributes?

**Comment by reb00ter** [comment]
https://www.rfc-editor.org/rfc/rfc8216#section-4.2

> An AttributeValue is one of the following:
   o  decimal-integer: an unquoted string of characters from the set
      [0..9] expressing an integer in base-10 arithmetic in the range
      from 0 to 2^64-1 (18446744073709551615).  A decimal-integer may be
      from 1 to 20 characters long.

**Comment by Beer4Ever83** [comment]
I beg to differ.
If you ask me, this is exactly the main difference between the M3U standard (as described in the RFC for HLS) and M3U Plus.
Let me explain by quoting the same RFC you mentioned.

The [attribute lists chapter](https://www.rfc-editor.org/rfc/rfc8216#section-4.2) says:
> Certain tags have values that are attribute-lists.
And, in fact, some tags like [#EXT-X-KEY](https://www.rfc-editor.org/rfc/rfc8216#section-4.3.2.4) or [#EXT-X-MAP](https://www.rfc-editor.org/rfc/rfc8216#section-4.3.2.5) support a list of attributes.

**But** there's no mention of attribute lists in the [#EXTINF](https://www.rfc-editor.org/rfc/rfc8216#section-4.3.2.1) tag. The fact that M3U Plus supports attribute lists on the #EXTINF row is a breaking change compared to the HLS standard.

This basically says that the syntax of an #EXTINF row in M3U Plus is not compliant with the HLS standard, including the format of attribute lists: they shall be quoted:
```
#EXTINF:-1, tvg-group="my-group" tvg-chno="1",My channel
```

I also did a quick search in Google and I haven't been able to find examples of unquoted attributes (numeric or not) on an #EXTINF row.

If you can provide an example (from a reliable source) of a playlist with unquoted attributes, I will consider to support this case but, until then, I'm afraid I have to reject this request.

**Comment by reb00ter** [comment]
Yes, attributing lists support in the #EXTINF tag is a breaking change. But they are attributes at first. Why do you mean, than #EXTINF attributes differs from others? Off course every number can be stored as string and got quotes in that case.
I have private iptv playlist with unquoted numeric attributes, required for existing player.

https://wiki.tvip.tv/en/m3u - this is not the same format that I have, but look at tvg-shift param. It's not just a number - it's a negative number

**Comment by Beer4Ever83** [comment]
The best I can do is to add a method to "sanitize" m3u files with unquoted numbers (see the PR attached to this issue).
As far as this library is concerned, the assumption is that the value of any attribute of an EXTINF row will always be surrounded by double quotes.
