### ISSUE TITLE
Export / save playlist

### ISSUE THREAD

**Issue by symbiosdotwiki** [Beer4Ever83/ipytv#72]
Hi, Is it possible to build / sort / export a playlist back to a m3u file after processing the data with this package?

**Comment by Beer4Ever83** [comment]
Hi!
yes, you can use the `to_m3u_plus_playlist()` method of an `M3UPlaylist` object.
This will return a string representation of your playlist in m3u format, then you can save it in a file.
Here's an example: 
```python
import os
import shutil
from ipytv import playlist
from ipytv.playlist import M3UPlaylist

path = "/path/to/input/file.m3u"
DIR = os.path.dirname(path)
FILE = os.path.basename(path)

def extract_groups(pl: M3UPlaylist) -> None:
    groups = pl.group_by_attribute(include_no_group=True)
    # Cleanup and recreate output directory
    if os.path.isdir(f"{DIR}/groups"):
        shutil.rmtree(f"{DIR}/groups")
    os.mkdir(f"{DIR}/groups")
    for group, channels in groups.items():
        new_pl = M3UPlaylist()
        new_pl.add_attributes(pl.get_attributes())
        for chan_index in channels:
            new_pl.append_channel(pl.get_channel(chan_index))
        sane_group = str(group).replace("/", "_")
        filename = f"{DIR}/groups/{sane_group}.m3u"
        with open(filename, "w", encoding="utf-8") as f:
            content = new_pl.to_m3u_plus_playlist()
            f.write(content)

pl = playlist.loadf(path)
extract_groups(pl)
```

The code above opens an M3U file then creates a `groups` folder in the same directory and then populates that folder with a bunch of `.m3u` files, one per every `GROUP_TITLE` attribute in the original playlist. Notice the `content = new_pl.to_m3u_plus_playlist()` instruction at the bottom of the function.
